### ISSUE TITLE
Compatibility with transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [snowleopard/selective#44]
See https://hackage.haskell.org/package/transformers-0.6.0.2/changelog.

Could you make a compatible release or revision? Thanks! :)

**Comment by snowleopard** [comment]
Sure, I'll try to have a look soon! Any help is welcome :)

**Comment by sjakobi** [comment]
I just noticed that the testsuite also depends on `mtl` which isn't compatible yet, but should be soon. So this is probably worth delaying until there's a compatible `mtl` release.

**Comment by snowleopard** [comment]
@sjakobi `mtl` is no longer a dependency.

**Comment by sjakobi** [comment]
Good! Unfortunately the testsuite still requires a compatible `mtl` via `tasty`.

**Comment by snowleopard** [comment]
Hah, I actually would like to drop a dependency on `tasty` too. The testsuite isn't really that complicated.

**Comment by snowleopard** [comment]
OK, the dependency on `tasty` is now gone.

**Comment by sjakobi** [comment]
@snowleopard Are you going to make a release or Hackage revision?

Alternatively, as a Hackage trustee, I can also revise the bounds on v0.4.2, if you like.

**Comment by snowleopard** [comment]
Yes, I'll release `selective-0.5` tomorrow.

**Comment by snowleopard** [comment]
Done: https://hackage.haskell.org/package/selective-0.5

**Comment by sjakobi** [comment]
Thank you, @snowleopard! :)

**Comment by snowleopard** [comment]
Thank you for driving this :-)
