### ISSUE TITLE
selectT doesn't need the Applicative instance

### ISSUE THREAD

**Issue by turion** [snowleopard/selective#53]
If you look closely at the definition https://hackage.haskell.org/package/selective-0.5/docs/src/Control.Selective.html#selectT you'll see that `Applicative f` isn't used:

```haskell
selectT :: (Applicative f, Traversable f) => f (Either a b) -> f (a -> b) -> f b
selectT x y = case sequenceA x of
    Left  a  -> ($a) <$> y
    Right fb -> fb
```

You only need `Functor f` which is implied by `Traversable f`. Probably you added `Applicative f` because it showed up in thought experiments like https://github.com/snowleopard/selective/issues/12#issuecomment-886053248. But there it is only necessary because `Applicative f` is the superclass constraint of `Selective f`.

**Comment by snowleopard** [comment]
Wait, isn't `Applicative f` used by `sequenceA`?

**Comment by turion** [comment]
`sequenceA :: (Traversable t, Applicative f) => t (f a) -> f (t a)`, so it uses just `Applicative (Either a)`.

**Comment by snowleopard** [comment]
Oh, indeed! Thanks -- fixing in #56.
