### ISSUE TITLE
Unexpected test success Tests.Validation.Theorems.Interchange

### ISSUE THREAD

**Issue by danwdart** [snowleopard/selective#59]
Hello, I get an unexpected test success when trying to compile selective 0.5 using ghc 9.4.

OK (expected failure): Tests.Validation.Theorems.(f <*> g) == (f `apS` g)

Unexpected test success:
    Tests.Validation.Theorems.Interchange: (x *> (y <*? z)) == ((x *> y) <*? z)

Has anyone got any idea there?

Thanks

**Comment by snowleopard** [comment]
This seems like a duplicate of #48. We fixed that but it looks like you're using an old version 0.5, which is missing the fix.

**Comment by snowleopard** [comment]
Ah, wait, it looks like we never released a newer version! I'll do that.

**Comment by danwdart** [comment]
Hah, super. Thanks!

**Comment by snowleopard** [comment]
Done: https://hackage.haskell.org/package/selective-0.6. Apologies for taking so long.
