### ISSUE TITLE
Paper links 404

### ISSUE THREAD

**Issue by avanov** [snowleopard/selective#76]
Hi!

Both the Hackage and Github README (https://github.com/snowleopard/selective#further-reading) links to the original paper are leading to a 404 page: https://www.staff.ncl.ac.uk/andrey.mokhov/selective-functors.pdf

Is this the same paper as (https://dl.acm.org/ft_gateway.cfm?id=3341694) that I see at the very top of the README section?

**Comment by snowleopard** [comment]
Thanks for letting me know. 

Yes, the link that works for you is fine.

Could you please check if the following link works for you too: https://doi.org/10.1145/3341694?

**Comment by avanov** [comment]
Yes, it works too. Thank you.

**Comment by snowleopard** [comment]
Thanks! Both links should be fixed now.
