### ISSUE TITLE
The link to the paper gives 404

### ISSUE THREAD

**Issue by Kleidukos** [snowleopard/selective#79]
Hi @snowleopard! I'm trying to access the paper at https://www.staff.ncl.ac.uk/andrey.mokhov/selective-functors.pdf but it returns a 404 now. Where is the new location? This is a bit problematic because it is in the documentation of the package. :)

**Comment by snowleopard** [comment]
The new and better link is ICFP official publication: https://dl.acm.org/doi/10.1145/3341694. It's open access, so let's use it.

I'll create a PR.

**Comment by snowleopard** [comment]
OK, PR #80 merged! Shall I nake a new release?

Thanks for letting me know :)

**Comment by Kleidukos** [comment]
I think you can get away with re-regenerating the Haddocks and publishing them for the current version. If you really care about making a new release it can be bundled in a 0.7.0.1 (in expanded PVP form). Not sure it warrants a 0.8.

**Comment by Kleidukos** [comment]
(btw, thanks for your reactivity <3)

**Comment by snowleopard** [comment]
I've uploaded 0.7.0.1. Sorry, I've lost a bit of reactivity here :)
